# Generated by Django 3.2.8 on 2021-11-25 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='total_vendas',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(default=1234, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itens_venda',
            name='carrinho',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='Digite a categoria do produto', max_length=50, verbose_name='Categoria do produto'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itens_venda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='itens_venda',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itens_venda',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.venda'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=20, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Digite o nome do produto', max_length=50, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cep_entrega',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='venda',
            name='frete',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
