# Generated by Django 3.2.8 on 2021-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20211125_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
