# Generated by Django 3.2.8 on 2021-11-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20211125_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
