# Generated by Django 3.2.8 on 2021-12-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_venda_logradouro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço unitário')),
                ('quantidade', models.IntegerField()),
                ('carrinho', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereço',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(default='sem endereço', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código'),
        ),
        migrations.DeleteModel(
            name='Itens_Venda',
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto'),
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.venda'),
        ),
    ]
