# Generated by Django 3.2.8 on 2022-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_itensvenda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, default='Sem descrição', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cep_entrega',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='logradouro',
            field=models.CharField(blank=True, help_text='(Rua, Condomínio, apartamento, etc...)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='previsao_entrega',
            field=models.DateField(verbose_name='Data prevista para entrega'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipoPagamento',
            field=models.CharField(max_length=50, verbose_name='Tipo de pagamento'),
        ),
    ]
