# Generated by Django 3.2.8 on 2022-02-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20220131_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade'),
        ),
    ]
